name: todoai_fe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  intl:
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^4.0.1
  dio: ^5.2.1
  http: ^0.13.6
  shared_preferences: ^2.1.2
  lottie: ^2.3.2
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.4.0
  iconify_flutter: ^0.0.5
  flutter_callkit_incoming: 1.0.3+3
  workmanager: ^0.5.1
  just_audio: ^0.9.28
  just_audio_background: ^0.0.1-beta.7
  home_widget: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/audios/
  fonts:
    - family: TodoAi-Bold
      fonts:
        - asset: assets/fonts/TodoAi-Bold.ttf

    - family: TodoAi-Book
      fonts:
        - asset: assets/fonts/TodoAi-Book.ttf

    - family: TodoAi-Medium
      fonts:
        - asset: assets/fonts/TodoAi-Medium.ttf
